default: &default
  plugins:
    - image
    - link
    - uploadimage
    - uploadimage

alternate:
  <<: *default
  toolbar: uploadimage | image | styleselect | bold italic | undo redo | table | preview
  plugins:
    - uploadimage
    - table
    - image
    - link
    - preview
